# Generated by Django 3.2.4 on 2021-06-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('cantHabitaciones', models.IntegerField()),
                ('cantSalas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservaSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('rut', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppHoteles.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('rut', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estadia', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppHoteles.hotel')),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
